### ISSUE TITLE
Deleting nodes in taxonomy doesn't work as expected

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#1]
1. Go to Taxonomy
2. Delete the node 
3. Page flashes (re-render rather than hard refresh) and the UI doesn't reflect the change
4. Refresh the page => the node is gone 

https://user-images.githubusercontent.com/34590602/108453233-3694b480-72be-11eb-9882-a8536d55e6bd.mp4

Similarly to this, I can't re-create my old node , say I deleted 'main' and I wanted to create 'main' again , it doesn't work 

https://user-images.githubusercontent.com/34590602/108453367-81163100-72be-11eb-889f-2a2283bd390e.mp4

**Comment by grasela** [comment]
@brendanmckenzie this also happens when you try to rename a node

**Comment by brendanmckenzie** [comment]
This is a bug.

Nodes are actually being updated, the UI just isn't refreshing to reflect.

**Comment by brendanmckenzie** [comment]
UI is now updated when deleting/renaming nodes
