### ISSUE TITLE
File type on media upload is wrong

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#11]
1. Upload a video, the file type is still showing image. 
2. I'd suggest detecting the file type upon upload 

<img width="672" alt="Screen Shot 2021-02-22 at 20 54 38" src="https://user-images.githubusercontent.com/34590602/108692026-3c092d80-7550-11eb-8a1c-e1818e2f706a.png">

**Comment by brendanmckenzie** [comment]
I actually think it is identifying the media type - it's just not pulling through to the UI... which is a bug (obviously).  Will fix.

**Comment by brendanmckenzie** [comment]
Resolved.
