### ISSUE TITLE
Deleting media items, simplifiy

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#12]
Can we just have an X or a delete button on each item, without having have to click into each one of them individually?
<img width="718" alt="Screen Shot 2021-02-22 at 20 52 16" src="https://user-images.githubusercontent.com/34590602/108691849-0bc18f00-7550-11eb-9153-cdfcef551072.png">

**Comment by brendanmckenzie** [comment]
Agreed.

You can actually drag items into the trash, but that isn't very clear or obvious - we will work on the UX of this.

**Comment by brendanmckenzie** [comment]
Resolved.
