### ISSUE TITLE
Can't delete media items (video)

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#13]
https://user-images.githubusercontent.com/34590602/108692304-8a1e3100-7550-11eb-9bc2-2d485727f70a.mp4

**Comment by brendanmckenzie** [comment]
I think this is another case where the item is deleted but the UI isn't updated.  Will fix.

**Comment by brendanmckenzie** [comment]
The delete button wasn't connected to anything 🙈 

Resolved.
