### ISSUE TITLE
Could we link out to creating a new entry of content rather than selecting only?(screenshot)

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#16]
<img width="1237" alt="Screen Shot 2021-02-22 at 21 07 44" src="https://user-images.githubusercontent.com/34590602/108693644-2c8ae400-7552-11eb-9413-f10fce19560c.png">

**Comment by brendanmckenzie** [comment]
Absolutely, that's a great idea.

**Comment by brendanmckenzie** [comment]
Resolved.  There's now an option to create a new entry as well as select an existing one.

After creating the entry it will be allocated to the value of the field that initiated the creation.  You can then save the entry and then navigate to the newly created entry to populate it.
