### ISSUE TITLE
Typing new field has got sketchy validation + skipping last character when deleting

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#2]
1. Type new field 
2. Jump around delete the characters
3. Last characters always stays in place
4. Validation is triggered even if this is a brand new field that hasn't been created before

https://user-images.githubusercontent.com/34590602/108687905-63113080-754b-11eb-800b-297f3a6db81e.mp4

**Comment by brendanmckenzie** [comment]
Nice find.

3 - this occurs because it doesn't update the field if it's been "touched" - since you focussed on the alias field it won't change it.  I'll investigate a way to make that nicer.

4 - this is a bug, will resolve.

**Comment by brendanmckenzie** [comment]
3 - 

On new models/fields the alias field will update on any change to the name of the model. 

If you enter the name of the model/field the alias will be populated, you can then update the alias, if you then go back and change the name the alias will be overwritten.  

On existing models/fields the alias will not change automatically with name changes.

4 - Resolved.
