### ISSUE TITLE
Can I quickly copy entries to create new entries?

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#20]
I've got 8 issues, I've created one page, with issue 1, I've got another 7, I want to just click 7 times, and go into each one of them and pick a different linked contents of Issue 
<img width="1266" alt="Screen Shot 2021-02-27 at 16 49 12" src="https://user-images.githubusercontent.com/34590602/109376926-ddf79400-791b-11eb-8fbc-b2efe4ee9ab9.png">

**Comment by brendanmckenzie** [comment]
Good idea.

We can add a "Duplicate" button for entries that will create a copy of the current entry.

**Comment by brendanmckenzie** [comment]
This will work at the Entry Version level.  You will be able to copy a version to a new entry.

**Comment by brendanmckenzie** [comment]
The UI will need work but the functionality is there.

In the version list on an entry, there is a "New entry" button that will copy the current selected version into a new entry.
