### ISSUE TITLE
Validation error doesn't go away

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#24]
<img width="750" alt="Screen Shot 2021-02-27 at 15 51 44" src="https://user-images.githubusercontent.com/34590602/109376980-4a729300-791c-11eb-992a-e3c56b9d1de7.png">

**Comment by brendanmckenzie** [comment]
Validation occurs on form submission, I can update the revalidation to occur on field blur rather than submission.

**Comment by brendanmckenzie** [comment]
Ah, this was actually because that field was dynamically generated.  Resolved, nonetheless.
