### ISSUE TITLE
Set maximum number of linked issues, can we have an option to set the current number as Maximum?

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#25]
<img width="742" alt="Screen Shot 2021-02-27 at 15 50 40" src="https://user-images.githubusercontent.com/34590602/109377001-683ff800-791c-11eb-99a4-f3fbf307f198.png">

**Comment by grasela** [comment]
This is kind of weird,as a user i don't know what that maximum is meant to do , can I not choose a maximum at all ? is that an option?

**Comment by brendanmckenzie** [comment]
These fields are both optional, it just limits the number of values you can have in the field.  I'll add some helper text to make that clearer.  I'll also add validation so that, if both set, the maximum must be greater than the minimum.
