### ISSUE TITLE
Confusing message when model is not unique

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#4]
'Model aliases must be unique'
That's confusing because I tried to find the model of the same alias and couldn't find it. Almost lost my patience .. before I realised the archived ones are counted for this too. This needs better communication

<img width="815" alt="Screen Shot 2021-02-19 at 15 42 33" src="https://user-images.githubusercontent.com/34590602/108688770-6527bf00-754c-11eb-9d39-83377ea6e509.png">

**Comment by brendanmckenzie** [comment]
I'll update the wording to indicate the conflict is with an archived model.

**Comment by brendanmckenzie** [comment]
I've altered the constraint - you can now create a new field with the alias of an archived field.

1. Create field called `foo`
2. Delete field called `foo`
3. Create field called `foo`

Original functionality - the reported error would show.

New functionality - a new field called `foo` will be created.

The same applies to models and aliases.  If you try to restore a deleted model with the same alias an error will show.

**Comment by brendanmckenzie** [comment]
I have temporarily disabled the ability to view and restore archived models while the UI flow is worked on.

This will be returned shortly.
