### ISSUE TITLE
Why am I seeing Hint on one of my modules? Shouldn’t I be seeing what I typed in?

### ISSUE THREAD

**Issue by grasela** [pokkocms/issues#7]
<img width="808" alt="Screen Shot 2021-02-22 at 20 36 39" src="https://user-images.githubusercontent.com/34590602/108690168-23981380-754e-11eb-9611-aaf50d99347c.png">

**Comment by brendanmckenzie** [comment]
Good point - "hint" is there for when you have multiple values in modular fields to help you quickly identify what each item in that field is.

We could look at ditching that approach for single value modular fields and just showing the editor (what shows when you click "Edit").

**Comment by brendanmckenzie** [comment]
"Hint" won't be shown on modular fields that are single values.

Multi-value modular fields will retain their original functionality.
